# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(938, 583)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 921, 531))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 692, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_15.setObjectName("checkBox_15")
        self.gridLayout_11.addWidget(self.checkBox_15, 7, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout_11.addWidget(self.label_30, 1, 0, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_50.setObjectName("label_50")
        self.gridLayout_11.addWidget(self.label_50, 7, 0, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_13.setObjectName("checkBox_13")
        self.gridLayout_11.addWidget(self.checkBox_13, 0, 1, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_11.addWidget(self.pushButton_15, 5, 4, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_11.addWidget(self.pushButton_13, 1, 4, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_39.setObjectName("label_39")
        self.gridLayout_11.addWidget(self.label_39, 4, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_38.setObjectName("label_38")
        self.gridLayout_11.addWidget(self.label_38, 3, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_23.setObjectName("pushButton_23")
        self.verticalLayout_12.addWidget(self.pushButton_23)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_28.setObjectName("pushButton_28")
        self.verticalLayout_12.addWidget(self.pushButton_28)
        self.horizontalLayout_11.addLayout(self.verticalLayout_12)
        self.comboBox_11 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_11.setObjectName("comboBox_11")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.comboBox_11.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_11)
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.label_44 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_44.setObjectName("label_44")
        self.gridLayout_15.addWidget(self.label_44, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_45.setObjectName("label_45")
        self.gridLayout_15.addWidget(self.label_45, 0, 0, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_32.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_15.addWidget(self.lineEdit_32, 1, 0, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_33.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_15.addWidget(self.lineEdit_33, 1, 1, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_46.setObjectName("label_46")
        self.gridLayout_15.addWidget(self.label_46, 0, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_34.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_15.addWidget(self.lineEdit_34, 1, 2, 1, 1)
        self.horizontalLayout_11.addLayout(self.gridLayout_15)
        self.gridLayout_11.addLayout(self.horizontalLayout_11, 2, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_34.setObjectName("label_34")
        self.gridLayout_11.addWidget(self.label_34, 0, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_54.setObjectName("label_54")
        self.gridLayout_11.addWidget(self.label_54, 5, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_25.setObjectName("pushButton_25")
        self.verticalLayout_11.addWidget(self.pushButton_25)
        self.pushButton_29 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_29.setObjectName("pushButton_29")
        self.verticalLayout_11.addWidget(self.pushButton_29)
        self.horizontalLayout_10.addLayout(self.verticalLayout_11)
        self.comboBox_10 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_10.setObjectName("comboBox_10")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.comboBox_10.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBox_10)
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_40.setObjectName("label_40")
        self.gridLayout_14.addWidget(self.label_40, 0, 1, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_41.setObjectName("label_41")
        self.gridLayout_14.addWidget(self.label_41, 0, 0, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_29.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_14.addWidget(self.lineEdit_29, 1, 0, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_30.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_14.addWidget(self.lineEdit_30, 1, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_42.setObjectName("label_42")
        self.gridLayout_14.addWidget(self.label_42, 0, 2, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_31.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_14.addWidget(self.lineEdit_31, 1, 2, 1, 1)
        self.horizontalLayout_10.addLayout(self.gridLayout_14)
        self.gridLayout_11.addLayout(self.horizontalLayout_10, 3, 2, 1, 1)
        self.checkBox_14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_14.setObjectName("checkBox_14")
        self.gridLayout_11.addWidget(self.checkBox_14, 2, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_11.addWidget(self.pushButton_11, 3, 4, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_11.addWidget(self.checkBox_9, 5, 1, 1, 1)
        self.checkBox_10 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_11.addWidget(self.checkBox_10, 3, 1, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_26.setObjectName("pushButton_26")
        self.verticalLayout_9.addWidget(self.pushButton_26)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_30.setObjectName("pushButton_30")
        self.verticalLayout_9.addWidget(self.pushButton_30)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.comboBox_8 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.horizontalLayout_8.addWidget(self.comboBox_8)
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_31 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_31.setObjectName("label_31")
        self.gridLayout_12.addWidget(self.label_31, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_32.setObjectName("label_32")
        self.gridLayout_12.addWidget(self.label_32, 0, 0, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_23.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_12.addWidget(self.lineEdit_23, 1, 0, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_24.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_12.addWidget(self.lineEdit_24, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_33.setObjectName("label_33")
        self.gridLayout_12.addWidget(self.label_33, 0, 2, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_25.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_12.addWidget(self.lineEdit_25, 1, 2, 1, 1)
        self.horizontalLayout_8.addLayout(self.gridLayout_12)
        self.gridLayout_11.addLayout(self.horizontalLayout_8, 4, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_11.addWidget(self.pushButton_14, 0, 4, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_43.setObjectName("label_43")
        self.gridLayout_11.addWidget(self.label_43, 2, 0, 1, 1)
        self.checkBox_11 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_11.setObjectName("checkBox_11")
        self.gridLayout_11.addWidget(self.checkBox_11, 4, 1, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_55.setObjectName("label_55")
        self.gridLayout_11.addWidget(self.label_55, 6, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_11.addWidget(self.pushButton_10, 4, 4, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_22.setObjectName("pushButton_22")
        self.verticalLayout_13.addWidget(self.pushButton_22)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_24.setObjectName("pushButton_24")
        self.verticalLayout_13.addWidget(self.pushButton_24)
        self.horizontalLayout_12.addLayout(self.verticalLayout_13)
        self.comboBox_12 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_12.setObjectName("comboBox_12")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.comboBox_12.addItem("")
        self.horizontalLayout_12.addWidget(self.comboBox_12)
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_47 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_47.setObjectName("label_47")
        self.gridLayout_16.addWidget(self.label_47, 0, 1, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_48.setObjectName("label_48")
        self.gridLayout_16.addWidget(self.label_48, 0, 0, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_35.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_16.addWidget(self.lineEdit_35, 1, 0, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_36.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_16.addWidget(self.lineEdit_36, 1, 1, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_49.setObjectName("label_49")
        self.gridLayout_16.addWidget(self.label_49, 0, 2, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_37.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_16.addWidget(self.lineEdit_37, 1, 2, 1, 1)
        self.horizontalLayout_12.addLayout(self.gridLayout_16)
        self.gridLayout_11.addLayout(self.horizontalLayout_12, 1, 2, 1, 1)
        self.checkBox_12 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_11.addWidget(self.checkBox_12, 6, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_11.addWidget(self.pushButton_12, 2, 4, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_16.setObjectName("checkBox_16")
        self.gridLayout_11.addWidget(self.checkBox_16, 1, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_10.addWidget(self.pushButton_3)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_10.addWidget(self.pushButton_21)
        self.horizontalLayout_9.addLayout(self.verticalLayout_10)
        self.comboBox_9 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_9)
        self.gridLayout_13 = QtWidgets.QGridLayout()
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.label_35 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_35.setObjectName("label_35")
        self.gridLayout_13.addWidget(self.label_35, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_36.setObjectName("label_36")
        self.gridLayout_13.addWidget(self.label_36, 0, 0, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_26.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_13.addWidget(self.lineEdit_26, 1, 0, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_27.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_13.addWidget(self.lineEdit_27, 1, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_37.setObjectName("label_37")
        self.gridLayout_13.addWidget(self.label_37, 0, 2, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_28.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_13.addWidget(self.lineEdit_28, 1, 2, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_13)
        self.gridLayout_11.addLayout(self.horizontalLayout_9, 0, 2, 1, 1)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_27.setObjectName("pushButton_27")
        self.verticalLayout_14.addWidget(self.pushButton_27)
        self.pushButton_31 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_31.setObjectName("pushButton_31")
        self.verticalLayout_14.addWidget(self.pushButton_31)
        self.horizontalLayout_13.addLayout(self.verticalLayout_14)
        self.comboBox_13 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_13.setObjectName("comboBox_13")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.comboBox_13.addItem("")
        self.horizontalLayout_13.addWidget(self.comboBox_13)
        self.gridLayout_17 = QtWidgets.QGridLayout()
        self.gridLayout_17.setObjectName("gridLayout_17")
        self.label_51 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_51.setObjectName("label_51")
        self.gridLayout_17.addWidget(self.label_51, 0, 1, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_52.setObjectName("label_52")
        self.gridLayout_17.addWidget(self.label_52, 0, 0, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_38.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_17.addWidget(self.lineEdit_38, 1, 0, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_39.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_17.addWidget(self.lineEdit_39, 1, 1, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_53.setObjectName("label_53")
        self.gridLayout_17.addWidget(self.label_53, 0, 2, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_40.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_17.addWidget(self.lineEdit_40, 1, 2, 1, 1)
        self.horizontalLayout_13.addLayout(self.gridLayout_17)
        self.gridLayout_11.addLayout(self.horizontalLayout_13, 5, 2, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_11.addWidget(self.pushButton, 0, 3, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_11.addWidget(self.pushButton_2, 1, 3, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_11.addWidget(self.pushButton_4, 2, 3, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_11.addWidget(self.pushButton_6, 3, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_11.addWidget(self.pushButton_17, 4, 3, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_11.addWidget(self.pushButton_18, 5, 3, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_11.addWidget(self.pushButton_19, 6, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_11.addWidget(self.pushButton_5, 7, 3, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_11.addWidget(self.pushButton_16, 6, 4, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_11.addWidget(self.pushButton_20, 7, 4, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 110, 241, 121))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_29 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_10.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_10.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_10.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_10.addWidget(self.pushButton_9, 3, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 241, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_3.addWidget(self.pushButton_7, 1, 1, 1, 1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(270, 20, 621, 351))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_18.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.graphicsView_9 = PlotWidget(self.gridLayoutWidget_4)
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.gridLayout_18.addWidget(self.graphicsView_9, 0, 1, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_56.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_56.setObjectName("label_56")
        self.gridLayout_18.addWidget(self.label_56, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 938, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.checkBox_15.setText(_translate("MainWindow", "Habilitar"))
        self.label_30.setText(_translate("MainWindow", "Canal 2"))
        self.label_50.setText(_translate("MainWindow", "Canal 8"))
        self.checkBox_13.setText(_translate("MainWindow", "Habilitar"))
        self.pushButton_15.setText(_translate("MainWindow", "Sonido"))
        self.pushButton_13.setText(_translate("MainWindow", "Sonido"))
        self.label_39.setText(_translate("MainWindow", "Canal 5"))
        self.label_38.setText(_translate("MainWindow", "Canal 4"))
        self.pushButton_23.setText(_translate("MainWindow", "  Impedancia  "))
        self.pushButton_28.setText(_translate("MainWindow", "Test"))
        self.comboBox_11.setItemText(0, _translate("MainWindow", "EEG"))
        self.comboBox_11.setItemText(1, _translate("MainWindow", "ECG"))
        self.comboBox_11.setItemText(2, _translate("MainWindow", "EMG"))
        self.comboBox_11.setItemText(3, _translate("MainWindow", "Manual"))
        self.label_44.setText(_translate("MainWindow", "tfc"))
        self.label_45.setText(_translate("MainWindow", "bfc"))
        self.label_46.setText(_translate("MainWindow", "Gain"))
        self.label_34.setText(_translate("MainWindow", "Canal 1"))
        self.label_54.setText(_translate("MainWindow", "Canal 6"))
        self.pushButton_25.setText(_translate("MainWindow", "  Impedancia  "))
        self.pushButton_29.setText(_translate("MainWindow", "Test"))
        self.comboBox_10.setItemText(0, _translate("MainWindow", "EEG"))
        self.comboBox_10.setItemText(1, _translate("MainWindow", "ECG"))
        self.comboBox_10.setItemText(2, _translate("MainWindow", "EMG"))
        self.comboBox_10.setItemText(3, _translate("MainWindow", "Manual"))
        self.label_40.setText(_translate("MainWindow", "tfc"))
        self.label_41.setText(_translate("MainWindow", "bfc"))
        self.label_42.setText(_translate("MainWindow", "Gain"))
        self.checkBox_14.setText(_translate("MainWindow", "Habilitar"))
        self.pushButton_11.setText(_translate("MainWindow", "Sonido"))
        self.checkBox_9.setText(_translate("MainWindow", "Habilitar"))
        self.checkBox_10.setText(_translate("MainWindow", "Habilitar"))
        self.pushButton_26.setText(_translate("MainWindow", "  Impedancia  "))
        self.pushButton_30.setText(_translate("MainWindow", "Test"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "EEG"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "ECG"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "EMG"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "Manual"))
        self.label_31.setText(_translate("MainWindow", "tfc"))
        self.label_32.setText(_translate("MainWindow", "bfc"))
        self.label_33.setText(_translate("MainWindow", "Gain"))
        self.pushButton_14.setText(_translate("MainWindow", "Sonido"))
        self.label_43.setText(_translate("MainWindow", "Canal 3"))
        self.checkBox_11.setText(_translate("MainWindow", "Habilitar"))
        self.label_55.setText(_translate("MainWindow", "Canal 7"))
        self.pushButton_10.setText(_translate("MainWindow", "Sonido"))
        self.pushButton_22.setText(_translate("MainWindow", "  Impedancia  "))
        self.pushButton_24.setText(_translate("MainWindow", "Test"))
        self.comboBox_12.setItemText(0, _translate("MainWindow", "EEG"))
        self.comboBox_12.setItemText(1, _translate("MainWindow", "ECG"))
        self.comboBox_12.setItemText(2, _translate("MainWindow", "EMG"))
        self.comboBox_12.setItemText(3, _translate("MainWindow", "Manual"))
        self.label_47.setText(_translate("MainWindow", "tfc"))
        self.label_48.setText(_translate("MainWindow", "bfc"))
        self.label_49.setText(_translate("MainWindow", "Gain"))
        self.checkBox_12.setText(_translate("MainWindow", "Habilitar"))
        self.pushButton_12.setText(_translate("MainWindow", "Sonido"))
        self.checkBox_16.setText(_translate("MainWindow", "Habilitar"))
        self.pushButton_3.setText(_translate("MainWindow", "  Impedancia  "))
        self.pushButton_21.setText(_translate("MainWindow", "Test"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "EEG"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "ECG"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "EMG"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "Manual"))
        self.label_35.setText(_translate("MainWindow", "tfc"))
        self.label_36.setText(_translate("MainWindow", "bfc"))
        self.label_37.setText(_translate("MainWindow", "Gain"))
        self.pushButton_27.setText(_translate("MainWindow", "  Impedancia  "))
        self.pushButton_31.setText(_translate("MainWindow", "Test"))
        self.comboBox_13.setItemText(0, _translate("MainWindow", "EEG"))
        self.comboBox_13.setItemText(1, _translate("MainWindow", "ECG"))
        self.comboBox_13.setItemText(2, _translate("MainWindow", "EMG"))
        self.comboBox_13.setItemText(3, _translate("MainWindow", "Manual"))
        self.label_51.setText(_translate("MainWindow", "tfc"))
        self.label_52.setText(_translate("MainWindow", "bfc"))
        self.label_53.setText(_translate("MainWindow", "Gain"))
        self.pushButton.setText(_translate("MainWindow", "Set"))
        self.pushButton_2.setText(_translate("MainWindow", "Set"))
        self.pushButton_4.setText(_translate("MainWindow", "Set"))
        self.pushButton_6.setText(_translate("MainWindow", "Set"))
        self.pushButton_17.setText(_translate("MainWindow", "Set"))
        self.pushButton_18.setText(_translate("MainWindow", "Set"))
        self.pushButton_19.setText(_translate("MainWindow", "Set"))
        self.pushButton_5.setText(_translate("MainWindow", "Set"))
        self.pushButton_16.setText(_translate("MainWindow", "Sonido"))
        self.pushButton_20.setText(_translate("MainWindow", "Sonido"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Ajustes"))
        self.label_29.setText(_translate("MainWindow", "Tiempo transcurrido"))
        self.pushButton_8.setText(_translate("MainWindow", "Iniciar"))
        self.label_5.setText(_translate("MainWindow", "Tiempo actual"))
        self.pushButton_9.setText(_translate("MainWindow", "Parar"))
        self.label_4.setText(_translate("MainWindow", "Dirección"))
        self.pushButton_7.setText(_translate("MainWindow", "Seleccionar"))
        self.label_56.setText(_translate("MainWindow", "Test"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Ejecutar"))
from pyqtgraph import PlotWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
